### ISSUE TITLE
Code Review: Empty string matches

### ISSUE THREAD

**Issue by sidprasad** [calebh/Juniper#1]
If I understand right, an empty case in F Sharp YACC matches an empty string.

In `Parser.fsy`, rules matching empty cases are considered non-idiomatic. It might be better to introduce some sort of `NULL` identifier for empty lists. Empty cases may cause your parser semantics to be slightly different than what you want if you are not careful, especially if you make further additions.

    funargList:
       | tyexpr ID COMMA funargList  {($1,$2) :: $4}
       | tyexpr ID                   {[($1,$2)]}
       |                               {[]}

**Comment by calebh** [comment]
No longer using yacc
