### ISSUE TITLE
[PROPOSAL] Dynamic Structures with Ownership Semantics and Implicit Lensing

### ISSUE THREAD

**Issue by Qata** [calebh/Juniper#18]
# Dynamic Structures with Ownership Semantics and Implicit Lensing

## Preamble

I'm still learning about uniqueness types, but there's probably a lot of overlap with my proposal, though I know there's some key differences.

## Motivation

In working with Juniper to write my light control program, I've encountered issues with stack memory limitations, leading to stack smashing when passing large models. While I’ve temporarily solved this by utilizing RTOS features for a larger stack, a more general solution involving safe dynamic memory allocation would be generally beneficial.

By enabling controlled dynamic memory management, Juniper would support larger, more complex models and position itself as a viable alternative to C++ for embedded applications.

The introduction of a new keyword, `dynamic`, would allow for values to be allocated on the heap, with a `free` call handled in the `deinit` method of the generated C++ wrapper.

### Declaration and Mutability

When the compiler encounters dynamic in a declaration, it requires that the following keyword is `mut`.
This informs users that `dynamic` types are always mutable in any context, reinforcing their use in cases for shared models.

```
let model: dynamic mut Model = createModel()
```

`dynamic` variables are safely mutable due to the ownership model, ensuring that no aliases can exist within the current scope. Only one reference to a `dynamic` variable can be passed or assigned at a time, and further attempts to duplicate the reference result in a compile-time error.

### Global Scope Behavior

If a `dynamic` variable is declared in the global scope, it will persist for the program’s lifetime and will not be automatically deallocated. This behaviour allows for static allocation of long-lived mutable resources.

```
// Due to global scope, `model_1` will never be deallocated.
let model_1 : dynamic mut Model = createModel()
```

### Function Return Types and Heap-Allocated Results

Functions that return a heap-allocated structure must explicitly use the `dynamic` keyword in the return type to signal that the result is allocated on the heap.

Under the hood, the returned value is a free-floating pointer, and the only valid usage of a function with a `dynamic` return type is assignment to a `dynamic mut` variable.

```
// The `dynamic` keyword is needed at this scope to ensure that the alias isn't created on the stack.
fun initialModel() : dynamic Model = {
    { value := 0u8 }
}
```

### Passing by Reference and Implicit Lensing

When a dynamic variable or sub-component is passed to a function, it can be passed as a pointer without additional syntax. 

Specifically:

Accessing a sub-component, like `model.sub_field`, directly gives the dereferenced value if the context is expecting a non-dynamic value. This could be considered default behaviour.

However:

When passing `model.sub_field` to a function that expects a dynamic parameter, the compiler automatically lenses it, treating it as a temporary, non-aliasable pointer.
This implicit lensing mechanism ensures efficient, pointer-based access to sub-components in function calls without additional syntax or accidental aliasing.
```
// Function expecting a `dynamic` parameter
fun process_subcomponent (component: dynamic SubComponentType) = {
    modify(component)
    ()
}

// Main function where `dynamic` model is created and passed
fun main() = {
    let model: dynamic mut Model = createModel()

     // Implicitly lenses `sub_field` as a pointer (`&(model->sub_field)`).
    process_subcomponent(model.sub_field)

    ()
}
```

#### Non-Aliasing Guarantees

Any attempt to create an alias of a dynamic variable within the same scope results in a compiler error. This behavior prevents accidental aliasing and ensures safe, single-owner handling of dynamically allocated values.

#### Aliasing Errors

Assigning one dynamic variable to another or passing the same sub-component to a function expecting a dynamic parameter multiple times will trigger a compile-time error to prevent aliasing.
```
let model_1 : dynamic mut Model = createModel()

// Compiler error: aliasing a dynamic value
let model_2 = model_1

// Compiler error: implicit aliasing of a dynamic value
// Can be implemented with a simple lexical comparison due to other aliasing rule.
multiplied(model.value, model.value)
```

#### Automatic Dereferencing and Literal Handling

Functions expecting a dynamic parameter cannot receive literals or stack-based values directly. This restriction enforces the allocation of primitive types like uint8 on the heap if they are passed to a function as dynamic.

```
// Compiler error: non-dynamic value passed to a function expecting a dynamic value
doubleIt(2)
```

#### Automatic Dereferencing in Non-Dynamic Contexts

When a dynamic variable is accessed in a non-dynamic context, it is dereferenced automatically, ensuring that the user works with the value directly. This behavior applies to all non-dynamic function parameters:

```
let display_model_properties(model: dynamic mut Model) = {
    // Automatic dereferencing of dynamic variable
    Serial.println(model.num_pixels)
}
```

## Examples

```
alias Model = {
    value : uint8
}

// Due to global scope, `model_1` will never be deallocated.
let model_1 : dynamic mut Model = createModel()

// The `dynamic` keyword is needed at this scope to ensure that the alias isn't created on the stack.
fun initialModel() : dynamic Model = {
    { value := 0u8 }
}

fun doubleIt(x : dynamic uint8) : unit = {
    // `dynamic` values are inherently mutable.
    x = x * 2
    ()
}

fun doubled(x : uint8) : uint8 = {
    x * 2
}

fun main() : unit = {
    let model_2 : dynamic mut Model = createModel()

    // Knowing the value is dynamic at this scope means that model_2 and model_3 are strictly equivalent.
    let model_3 : dynamic mut Model = { value := 0u8 }

    // Since the function expects a dynamic value, this compiles to `&(model_2->value)`.
    fun doubleIt(model_2.value)

    // Since the function expects a stack value, this compiles to `model_2->value`.
    fun doubled(model_2.value)
    
    // `model_2 and model_3` will be automatically deallocated upon scope exit.
    ()
}
```

```
alias Model = {
    value : uint8
}

fun doubleIt(x : dynamic uint8) : unit = {
    // `dynamic` values are inherently mutable.
    x = x * 2
    ()
}

fun multiplied(x : dynamic uint8, y : dynamic uint8) : uint8 = {
    x * y
}

fun main() : unit = {
    let model_1 : dynamic mut Model = createModel()

    // Compiler error: aliasing a dynamic value
    let model_2 = model_1

    // Compiler error: implicit aliasing of a dynamic value.
    // Can be implemented with a simple string comparison due to other aliasing rule.
    multiplied(model.value, model.value)

    // Compiler error: non-dynamic value passed to a function expecting a dynamic value.
    doubleIt(2)

    ()
}
```

**Comment by calebh** [comment]
At the present moment we can use heap allocated values in Juniper via the `ref` keyword. and associated type. You can mutate ref cells by either clearing the entire thing, or mutating specific members:

```
{
    let foo = ref { x:= true, y := 10u32 }
    // Set foo in its entirety
    *foo = { x:= false, y := foo->y}
    // Set the y member of foo
    foo->y = 10u32
    // Pass a reference to the heap cell in an inout parameter
    // when myfun mutates its parameter, it actually mutates the contents of the ref cell
    myfun(inout *foo)
    // when myfun2 mutates its parameter, it actually mutates the contents of foo->y
    myfun2(inout foo->y)
}
```

ref cells work fine with inout parameters as well, by using the dereference operation. The inout operator also works fine with lensing.

Overall, I favor annotation of heap allocation at the expression level vs implicit at the type level. This is similar to the use of the `new` keyword in C++.

Allowing ref cells to operate without a counter is a different story. I have seen some languages that use static analysis to remove counter increments/decrements where possible and keep them otherwise. This seems like a good tradeoff to me.

If Juniper were to have fully recursive datatypes, we would need a better story around heap allocation. A simple example is a linked list, constructed out of `nil` and a bunch of `cons` cells. Would it be okay for the user to mutate a ref cell in the middle of a linked list? A functional programmer would shudder at this possibility, but this is perfectly fine in any imperative language.

At the same time, I don't think someone working with linked lists would want to sprinkle `ref` expressions and `*` deref operations everywhere. This seems pretty unergonomic.

**Comment by Qata** [comment]
It’d been a few months since I read the docs, totally missed the ref type somehow.
