### ISSUE TITLE
Unable to compile C++: Shadowed parameter

### ISSUE THREAD

**Issue by Qata** [calebh/Juniper#21]
`Compilation error: declaration of 'Prelude::maybe<juniper::records::recordt_8<Prelude::maybe<unsigned char>, NeoPixel::Function, long unsigned int, juniper::records::recordt_1<long unsigned int> > >& operation' shadows a parameter`

https://github.com/Qata/Kindling/commit/9cf5f70ff02a3f13965bd1c6c70f8bbc59791e1a

**Comment by calebh** [comment]
Issue fixed in bece86b

**Comment by calebh** [comment]
If you want a mutable argument, you can add the `mut` annotation to the argument. Like this:

```
fun foo(mut myrecord : { x : bool, y : uint32}) = {
    myrecord.x = false
    myrecord
}
```

**Comment by Qata** [comment]
Oh awesome! That’s not in the docs so I didn’t even try it, been conditioned by Swift to not expect that to work haha
