### ISSUE TITLE
Strings containing escaped characters are evaluated by the compiler, resulting in non-compiling code

### ISSUE THREAD

**Issue by Qata** [calebh/Juniper#24]
Not critical, easily worked around using `\\`.

The strings "\n" and "\r" are evaluated to newline by the compiler, resulting in broken C++.

**Comment by calebh** [comment]
This issue has been resolved. I am planning on putting together the Juniper 4.0.1 release soon which will have this fix, and fixes for the other issues that @Qata submitted.
