### ISSUE TITLE
Code Review: Documentation

### ISSUE THREAD

**Issue by sunjayBhatia** [calebh/Juniper#3]
Add documentation on how to build, run, description of repository at the least.

Helpful inclusions in `README.md` and beyond:
* links to dependencies/frameworks used
* setup guide
* language overview
  * AST/grammar/etc.
* `examples` directory for simple Juniper code snippets
  * these can evolve as you progress
  * potentially will help with organization, new features, keeping you on track etc.
  * think of these as an equivalent to unit tests

**Comment by calebh** [comment]
Documentation added a while ago
